### ISSUE TITLE
Sending segment batch failed with: NoCredentialProviders: no valid provider

### ISSUE THREAD

**Issue by Hassan1175** [aws/aws-xray-daemon#59] opened 2020-07-20 16:14 UTC
I am running daemon locally for my Django project to get traces.
I have configured the credentials in environment variables and ~/.aws/credentials file as well. But still facing that issue. Can anybody please help me in figuring out issue.
The error which I am facing is

Sending segment batch failed with: NoCredentialProviders: no valid provider

PS: I am using AWS-Xrays for Python. My OS is Ubuntu 18.04.

@awssandra

**Comment by lupengamzn** [comment] 2020-07-27 17:26
Hi @Hassan1175 

The reason is because the Deamon can't properly access the AWS Credentials. This may be due to user permission or some typo in credential file.

Can you try modifying the access permission of `~/.aws` folder and make sure there is no typo in `~/.aws/credentials` file?

**Comment by willarmiros** [comment] 2021-01-14 17:29
Closing as duplicate of #48. If there are further details or questions relating to this bug please post them their to assist our investigations.

**Closed by willarmiros** 2021-01-14 17:29 UTC

**Comment by drumadrian** [comment] 2022-04-02 01:21
I got this error when my version of the x-ray deamon was old. 

Follow this as guidance to update your x-ray deamon if it is running on ECS:

https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html
